name = "I was transported to another world where, alone, I mined and crafted to become the hero「Bryan」"
author = "AnimeEnjoyer"
version = "2026.03.10-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "320791e3645998b4033a6e323438218c59165593eb1dfeed21d21782954c92a6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
