name = "I was transported to another world where, alone, I became the hero known as Bryan"
author = "AnimeEnjoyer"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42b245f68e4fae24cb7c1a33b8d45a5f8dab1e267eed94136cfbb0c1b4bdf575"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
