name = "I was transported to another world where, alone, I mined and crafted to become the hero「Bryan」"
author = "AnimeEnjoyer"
version = "2025.11.09"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0443d146689d4da193150f084514b266e8c33c1c97ff82dca32c84d760086346"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
