name = "I was transported to another world where, alone, I mined and crafted to become the hero「Bryan」"
author = "AnimeEnjoyer"
version = "2026.01.26-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f0cb914984c466b3fb26c1a2019f5923a20f6b196d7760061a43714863e2c76"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
