name = "I was transported to another world where, alone, I mined and crafted to become the hero「Bryan」"
author = "AnimeEnjoyer"
version = "4.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3095e4f6850bc00b5f0e705a81af501337a3249350f92bb716f62c108c7e413"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
