name = "I was transported to another world where, alone, I mined and crafted to become the hero「Bryan」"
author = "AnimeEnjoyer"
version = "3.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051288c9063046e6100ddbbb6ebb3a4922cdcb71a99bb3f22182d44ab399e826"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
