name = "I was transported to another world where, alone, I became the hero known as Bryan"
author = "AnimeEnjoyer"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8267b2778fa608681a7603abf57ea0eab39ed3a8a4d45e62bf1c09821834c51"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
