name = "I was transported to another world where, alone, I became the hero known as Bryan"
author = "AnimeEnjoyer"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e951ac4a9a417a1e6365fb42fa5e3109d2e890ec8ebe78d649c32ed3558ba868"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
