
#Enable/Disable Meat
[meat]
	#Enable Allay Meat?
	enableAllayMeat = false
	#Enable Axolotl Meat?
	enableAxolotlMeat = true
	#Enable Bat Meat?
	enableBatMeat = true
	#Enable Bee Meat?
	enableBeeMeat = false
	#Enable Camel Meat?
	enableCamelMeat = true
	#Enable Cat Meat from Cats?
	enableCatMeat = true
	#Enable Dolphin Meat?
	enableDolphinMeat = true
	#Enable Horse Meat from Donkeys?
	enableDonkeyMeat = true
	#Enable Glow Squid Meat?
	enableGlowSquidMeat = true
	#Enable Fox Meat?
	enableFoxMeat = true
	#Enable Frog Meat?
	enableFrogMeat = true
	#Enable Goat Meat?
	enableGoatMeat = true
	#Enable Horse Meat from Horses?
	enableHorseMeat = true
	#Enable Iron Golem Meat?
	enableIronGolemMeat = false
	#Enable Llama Meat from Llamas?
	enableLlamaMeat = true
	#Enable Horse Meat from Mules?
	enableMuleMeat = true
	#Enable Cat Meat from Ocelots?
	enableOcelotMeat = true
	#Enable Bear Meat from Pandas?
	enablePandaMeat = true
	#Enable Parrot Meat?
	enableParrotMeat = false
	#Enable Piglin Porkchops from Piglins?
	enablePiglinMeat = true
	#Enable Piglin Porkchops from Pigling Brutes?
	enablePiglinBruteMeat = true
	#Enable Bear Meat from Polar Bears?
	enablePolarBearMeat = true
	#Enable Sniffer Meat?
	enableSnifferMeat = true
	#Enable Squid Meat?
	enableSquidMeat = true
	#Enable Strider Meat?
	enableStriderMeat = true
	#Enable Llama Meat from Trader Llamas?
	enableTraderLlamasMeat = true
	#Enable Turtle Meat?
	enableTurtleMeat = true
	#Enable Villager Meat from Villagers? (Also affects noses)
	enableVillagerMeat = true
	#Enable Villager Meat from Wandering Traders? (Also affects noses)
	enableWanderingTraderMeat = true
	#Enable Wolf Meat?
	enableWolfMeat = true

#Enable/Disable Butcher Trades
[trades]
	#Enable Bear Meat Trades? (Default: True)
	enableBearMeatTrades = true
	#Enable Camel Meat Trades? (Default: True)
	enableCamelMeatTrades = true
	#Enable Fox Meat Trades? (Default: True)
	enableFoxMeatTrades = true
	#Enable Frog Meat Trades? (Default: True)
	enableFrogMeatTrades = true
	#Enable Goat Meat Trades? (Default: True)
	enableGoatMeatTrades = true
	#Enable Horse Meat Trades? (Default: True)
	enableHorseMeatTrades = true
	#Enable Llama Meat Trades? (Default: True)
	enableLlamaMeatTrades = true
	#Enable Squid Meat Trades? (Default: True)
	enableSquidMeatTrades = true
	#Enable Wolf Meat Trades? (Default: True)
	enableWolfMeatTrades = true
	#Enable Allay Meat Trades? (Default: False)
	enableAllayMeatTrades = false
	#Enable Axolotl Meat Trades? (Default: False)
	enableAxolotlMeatTrades = false
	#Enable Bat Meat Trades? (Default: False)
	enableBatMeatTrades = false
	#Enable Bee Meat Trades? (Default: False)
	enableBeeMeatTrades = false
	#Enable Cat Meat Trades? (Default: False)
	enableCatMeatTrades = false
	#Enable Dolphin Meat Trades? (Default: False)
	enableDolphinMeatTrades = false
	#Enable Iron Golem Meat Trades? (Default: False)
	enableIronGolemMeatTrades = false
	#Enable Parrot Meat Trades? (Default: False)
	enableParrotMeatTrades = false
	#Enable Piglin Porkchop Trades? (Default: False)
	enablePiglinPorkchopTrades = false
	#Enable Sniffer Meat Trades? (Default: False)
	enableSnifferMeatTrades = false
	#Enable Strider Meat Trades? (Default: False)
	enableStriderMeatTrades = false
	#Enable Turtle Meat Trades? (Default: False)
	enableTurtleMeatTrades = false
	#Enable Villager Meat Trades? (Default: False)
	enableVillagerMeatTrades = false

